# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: 50.002 Computation Structures
description: >- # this means to ignore newlines until "baseurl:"
  From Transistors to Operating System
baseurl: "/computationstructures" # the subpath of the site
url: "https://natalieagus.github.io" # the base hostname & protocol for the site


header:
  pages:
    - name: Home
      slug: /
    - name: Notes
    - name: Exercise
    - name: Labs
    - name: FPGA

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: natalie_agus@sutd.edu.sg
      link: mailto:natalie_agus@sutd.edu.sg


collections:
  problemsets: 
    output: true
  lecturenotes: 
    output: true
  fpga: 
    output: true
  labs:
    output: true

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
sass:
    style: :compressed
plugins:
  - jekyll-feed


# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
